[package]
name = "ergogen-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
ergogen-pcb = { path = "../ergogen-pcb", features = ["js-footprints-wasm"] }
wasm-bindgen-test = "0.3"
