[package]
name = "ergogen-layout"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ergogen-core = { path = "../ergogen-core" }
ergogen-parser = { path = "../ergogen-parser" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true