[package]
name = "ergogen-export"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ergogen-core = { path = "../ergogen-core" }
dxf.workspace = true
svg.workspace = true
serde.workspace = true
anyhow.workspace = true
